jobs:
  ReportsFalsePositiveCheck:
    enabled: true

  ManualTriggerBIC:
    enabled: false

  ThresholdExceeded:
    enabled: false

  UPSReport:
    enabled: false

  CancelCopyJobsTickets:
    enabled: true
